spring.application.name=demo1
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=niki
spring.security.user.password=1234
#server.servlet.session.cookie.same-site=strict
jwt.secret=NTJjYzY5YjAtYTk2Mi00Y2U4LThhN2ItM2E0ODZmZjE5Yzc3Njc0NzI2ZTctZTc3
jwt.expiration=300000
